/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daftarUkm;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class tofatek extends javax.swing.JFrame {

    /**
     * Creates new form tofatek
     */
    public tofatek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgKelamin = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fAlasan = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        fTlp = new javax.swing.JTextField();
        fAlamat = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        fNim = new javax.swing.JTextField();
        fNama = new javax.swing.JTextField();
        cProdi = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Nama Lengkap :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 140, 100, 15);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("NIM :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 50, 15);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Program Studi :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 220, 110, 15);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText(" Alamat :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 260, 70, 15);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Jenis Kelamin :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(69, 297, 100, 15);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Alasan ingin bergabung :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(69, 379, 160, 15);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("No. Telpon :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(69, 337, 90, 15);

        fAlasan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(fAlasan);
        fAlasan.setBounds(69, 407, 377, 102);

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan);
        bSimpan.setBounds(69, 521, 72, 23);

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        getContentPane().add(bReset);
        bReset.setBounds(224, 521, 72, 23);

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar);
        bKeluar.setBounds(374, 521, 72, 23);

        fTlp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(fTlp);
        fTlp.setBounds(220, 330, 229, 30);

        fAlamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(fAlamat);
        fAlamat.setBounds(220, 250, 229, 30);

        bgKelamin.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbLaki.setText("Laki-Laki");
        getContentPane().add(rbLaki);
        rbLaki.setBounds(220, 295, 110, 20);

        bgKelamin.add(rbPerempuan);
        rbPerempuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(345, 295, 110, 20);

        fNim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(fNim);
        fNim.setBounds(220, 170, 229, 30);

        fNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(fNama);
        fNama.setBounds(220, 130, 229, 30);

        cProdi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Prodi --", "Sistem Informasi", "Teknik Informatika", "Teknik Industri", "Teknik Mesin", "Teknik Elektronika", "Teknik Mekatronika" }));
        cProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cProdiActionPerformed(evt);
            }
        });
        getContentPane().add(cProdi);
        cProdi.setBounds(220, 210, 229, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daftarUkm/LOGO UTM BARU kcl.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(50, 30, 73, 73);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\LOGO tofatek kcl.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 30, 100, 73);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel1.setText("FORMULIR PENDAFTARAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 50, 162, 16);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel10.setText("UKMF-TOFATEK 2023");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 80, 128, 16);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\bg 4.jpg")); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 520, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String nama = fNama.getText();
        String nim = fNim.getText();
        String selectedItem = cProdi.getSelectedItem().toString();     
        String alamat = fAlamat.getText();
        String jenisKelamin = "";
        if (rbLaki.isSelected()) {
            jenisKelamin = "Laki-laki";
        } else if (rbPerempuan.isSelected()) {
            jenisKelamin = "Perempuan";
        }
        String telpon = fTlp.getText();
        String alasan = fAlasan.getText();
        
        JOptionPane.showMessageDialog(this, "Data kamu berhasil disimpan sebagai berikut : \n Nama : " + nama + "\n Nim : " + nim + "\n Prodi : " + selectedItem + "\n Alamat : " + alamat + "\n Jenis Kelamin : " + jenisKelamin + "\n No. Telp : " + telpon + "\n Alasan bergabung : " + alasan);
    }//GEN-LAST:event_bSimpanActionPerformed

    private void cProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cProdiActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        fNama.setText("");
        fNim.setText("");
        cProdi.setSelectedItem("-- Pilih Prodi --");
        fAlamat.setText("");
        bgKelamin.clearSelection();
        fTlp.setText("");
        fAlasan.setText("");
    }//GEN-LAST:event_bResetActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tofatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tofatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tofatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tofatek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tofatek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup bgKelamin;
    private javax.swing.JComboBox<String> cProdi;
    private javax.swing.JTextField fAlamat;
    private javax.swing.JTextField fAlasan;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField fNim;
    private javax.swing.JTextField fTlp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    // End of variables declaration//GEN-END:variables
}
