

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//package countDown;

/**
 *
 * @author LENOVO
 */
public class ujian extends javax.swing.JFrame {
    
    private int waktuTersisa = 30; // Waktu awal dalam detik
    private Timer timer;
    
    /**
     * Creates new form ujian
     */
    public ujian() {
        initComponents();
        
        fHitung.setEditable(false); // Membuat JTextField hanya tampilan
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                waktuTersisa--;
                fHitung.setText(String.valueOf(waktuTersisa));

                if (waktuTersisa == 0) {
                    timer.stop();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bMulai = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fHitung = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bHenti = new javax.swing.JButton();
        fJawab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel1.setText("JAWAB PERTANYAAN DIBAWAH INI DENGAN CEPAT!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 560, 29);

        bMulai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bMulai.setText("Mulai");
        bMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMulaiActionPerformed(evt);
            }
        });
        getContentPane().add(bMulai);
        bMulai.setBounds(140, 350, 136, 51);

        bKeluar.setBackground(new java.awt.Color(153, 153, 255));
        bKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar);
        bKeluar.setBounds(530, 430, 72, 23);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("27 + 14 + 9 + 13 + 6 + 19 + 1 + 0 + 5 + 14 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 210, 454, 28);

        fHitung.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        fHitung.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fHitung.setText("30");
        fHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fHitungActionPerformed(evt);
            }
        });
        getContentPane().add(fHitung);
        fHitung.setBounds(240, 80, 130, 78);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Jawaban mu adalah        =");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 280, 240, 22);

        bHenti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bHenti.setText("Jawab");
        bHenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHentiActionPerformed(evt);
            }
        });
        getContentPane().add(bHenti);
        bHenti.setBounds(340, 350, 136, 51);

        fJawab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fJawab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(fJawab);
        fJawab.setBounds(370, 260, 142, 58);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Waktu     : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 140, 67, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("detik");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 140, 30, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\bg kertas.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 630, 470);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 80);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMulaiActionPerformed
        // TODO add your handling code here:
        timer.start(); // Memulai hitung mundur saat tombol "Mulai" ditekan
    }//GEN-LAST:event_bMulaiActionPerformed

    private void bHentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHentiActionPerformed
        // TODO add your handling code here:
        String inputText = fJawab.getText();
        try {
            int inputNumber = Integer.parseInt(inputText);
            if (inputNumber == 108) {
                timer.stop(); // Menghentikan hitung mundur jika angka yang dimasukkan adalah 108
            }
        } catch (NumberFormatException ex) {
            // Tangani kesalahan jika masukan tidak berupa angka
        }
    }//GEN-LAST:event_bHentiActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void fHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fHitungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ujian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ujian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHenti;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bMulai;
    private javax.swing.JTextField fHitung;
    private javax.swing.JTextField fJawab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
